# Generated by Django 3.0.3 on 2020-05-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=150)),
                ('mail_id', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
