# Generated by Django 3.0.3 on 2020-05-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girisha', '0002_auto_20200501_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
