# Generated by Django 3.0.3 on 2020-05-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girisha', '0003_auto_20200501_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
