# Generated by Django 3.0.3 on 2020-05-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20200513_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
