# Generated by Django 3.0.5 on 2020-05-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='image',
            field=models.FileField(upload_to='profilepics/'),
        ),
    ]
