# Generated by Django 3.0.3 on 2020-05-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0002_auto_20200502_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='image',
            field=models.ImageField(upload_to='profilepics/'),
        ),
    ]
