# Generated by Django 3.0.3 on 2020-05-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_auto_20200505_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='password',
            field=models.CharField(default='password@123', max_length=150),
        ),
    ]
