# Generated by Django 3.0.3 on 2020-05-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_userregister_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='mailid',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
