# Generated by Django 3.0.3 on 2020-04-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.CharField(max_length=10)),
                ('stuName', models.CharField(max_length=50)),
                ('branch', models.CharField(choices=[('CES', 'cse'), ('ECE', 'ece'), ('IT', 'it'), ('EEE', 'eee')], max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
