# Generated by Django 3.0.3 on 2020-04-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='language',
            field=models.CharField(blank=True, choices=[('T', 'Telugu'), ('E', 'English'), ('H', 'Hindi')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('cse', 'CES'), ('ece', 'ECE'), ('it', 'IT'), ('eee', 'EEE')], max_length=50),
        ),
    ]
