# Generated by Django 3.0.3 on 2020-04-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp2', '0002_auto_20200429_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('cse', 'CSE'), ('ece', 'ECE'), ('it', 'IT'), ('eee', 'EEE')], max_length=50),
        ),
    ]
